Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace operator_denemesi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        
       
    }
}

Controllers/calisiyorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace operator_denemesi.Controllers
{
    public class calisiyorController : Controller
    {
        // GET: calisiyor
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Calisiyor()
        {
            return View();
        }

        public ActionResult DurusNedeni()
        {
            return View();
        }

        public ActionResult OperasyonProseduru()
        {
            return View(); 
        }

        public ActionResult HataGirisi()
        {
            return View();
        }
        
        public ActionResult DigerIslemler()
        {
            return View();
        }

        public ActionResult IsBilgileri()
        {
            return View();
        }

        public ActionResult IsDegistir()
        {
            return View();
        }

        public ActionResult IsDegistir2()
        {
            return View();
        }
       
        public ActionResult IsDetayi2()
        {
            return View();
        }
    }
}

Controllers/isBekliyorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace operator_denemesi.Controllers
{
    public class isBekliyorController : Controller
    {
        // GET: isBekliyor
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult isbekliyor()
        {
            return View();
        }

        public ActionResult isYukle()
        {
            return View();
        }

        public ActionResult isYukle2()
        {
            return View();
        }

        public ActionResult isDetayi()
        {
            return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/calisiyor/Calisiyor.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <script src="~/myScript.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <title>Calisiyor</title>
</head>
<body>
    <div class="row">
        <div class="col-md-6" style="background-color:darkred">
            <p style="color:white"><strong>İSTASYON 899</strong></p>
        </div>

        <div class="col-md-6" style="background-color:limegreen"><p style="color:white"><strong>ÇALIŞIYOR</strong></p></div>
    </div>

    <div class="container-fluid" style="background-color:darkslategrey; height:100px">
        <div class="row">
            <div class="col-md-6">
                <label style="color:white">İŞ NO | PLAN. İŞ MİKTARI</label>
                <label style="color:limegreen">2855 | 13000</label><br />
                <label style="color:white">KALAN MİKTAR [ADET]</label>
                <label style="color:limegreen">[KÜ: 11656] 1296</label>
            </div>
            <div class="col-md-6">
                <label style="color:white"><strong>ADET</strong></label><br />
            </div>
        </div>
    </div>

    <div class="container-fluid" style="background-color:darkred; height:80px">
        <div class="row">
            <div class="col-md-6">
                <label style="color:white">STOK</label><br />
                <label style="color:white">STOK ADI 2</label>
            </div>
            <div class="col-md-6">
                <label style="color:white">İŞ EMRİ NO</label><br />
                <label style="color:white">İŞE BAŞLAMA</label><br />
                <label style="color:white">GEÇEN SÜRE</label>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <th scope="row">PERSONEL</th>
                            <td>Personel 955</td>
                        </tr>
                        <tr>
                            <th scope="row">OPERASYON</th>
                            <td>075-Prograsiv</td>
                        </tr>
                        <tr>
                            <th scope="row">ANLIK DURUŞ SÜRESİ</th>
                            <td></td>
                        </tr>
                        <tr>
                            <th scope="row">VARDİYA ÜRETİMİ</th>
                            <td>9</td>
                        </tr>
                        <tr>
                            <th scope="row">VARDİYA DURUŞ SÜRESİ</th>
                            <td>2 sa 37 dk</td>
                        </tr>
                        <tr>
                            <th scope="row">RANDIMAN (Son 8 saat)</th>
                            <td>%2</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="col-md-6">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <th scope="row">HATA</th>
                            <td>0</td>
                        </tr>
                        <tr>
                            <th scope="row">TAKİP NO</th>
                            <td>008290</td>
                        </tr>
                        <tr>
                            <th scope="row">EKİPMAN</th>
                            <td>55129-02030-00</td>
                        </tr>
                        <tr>
                            <th scope="row">ANLIK/V. ORT. HIZ</th>
                            <td>1800/0</td>
                        </tr>
                        <tr>
                            <th scope="row">ÇEVRİM G/P</th>
                            <td>2/1.5</td>
                        </tr>
                        <tr>
                            <th scope="row">PLAN. KAPASİTE</th>
                            <td>2400 Ad/Sa</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    @*<div class="text-center">
        <button type="button" class="btn btn-success btn-lg">İş Yükle</button>
        <button type="button" class="btn btn-success btn-lg">Duruş Tanımla</button>
        <button type="button" class="btn btn-success btn-lg">Personel İşlemleri</button>
        <button type="button" class="btn btn-success btn-lg">Hata Girişi</button>
        <button type="button" class="btn btn-success btn-lg">Vardiya Bilgileri</button>
        <button type="button" class="btn btn-success btn-lg">İş Parametreleri</button>
        <a class="btn btn-success btn-lg" href="@Url.Action("DigerIslemler","calisiyor")"></a>
        <button type="button" class="btn btn-success btn-lg">Diğer İşlemler</button>
    </div>*@

    @*<br />
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    <div style="height:100px; width:160px; border:2px solid gray">
                        <img src="~/Content/images/login.png" height="60" width="70" />
                        <label>Barış Usta</label><br />
                        <label>Sicil: 001</label>
                    </div>
                    <label>Makine: Freze</label><br />
                    <label>Parça Adı: Dişli</label>
                </div>
                <div class="col-md-6">
                    <header><strong>PERFORMANS DURUMU</strong></header>
                    <div style="height:140px; width:250px; border:2px solid gray">
                        <div class="row" style="text-align:center"><label>Freze OEE</label><br /></div>
                        <div id="chartOEE"> </div>
                    </div>
                </div>
            </div>
        </div>*@
        <br /><br />


            <div class="text-center">
                <button class="btn btn-warning btn-lg" onclick='window.location = "@Url.Action("OperasyonProseduru", "calisiyor")";'>OPERASYON PROSEDÜRÜNE BAK</button>
                <button class="btn btn-warning btn-lg">İŞ BİTİR</button>
                <button class="btn btn-warning btn-lg" onclick='window.location = "@Url.Action("DurusNedeni","calisiyor")";'>DURAKLAT/DURUŞ NEDENİ GİR</button>
                <button class="btn btn-warning btn-lg">HATA GİRİŞİ</button>
            </div>


            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
            <script>
                var options = {
                    chart: {
                        height: 140,
                        type: "radialBar"
                    },

                    series: [92],

                    plotOptions: {
                        radialBar: {
                            hollow: {
                                margin: 15,
                                size: "70%"
                            },

                            dataLabels: {
                                showOn: "always",
                                name: {
                                    offsetY: -10,
                                    show: true,
                                    color: "#888",
                                    fontSize: "13px"
                                },
                                value: {
                                    color: "#111",
                                    fontSize: "20px",
                                    show: true
                                }
                            }
                        }
                    },

                    stroke: {
                        lineCap: "round",
                    },
                    labels: [""]
                };



                var chart1 = new ApexCharts(document.querySelector("#chartOEE"), options);

                chart1.render();

            </script>
</body>
</html>

Views/calisiyor/DigerIslemler.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>DigerIslemler</title>
</head>
<body>
    <div class="row"><h2 style="text-align:center; background-color:khaki">DİĞER İŞLEMLER</h2></div>
    <br /><br />
    <div class="container">
        <div class="row">
            <div class="col-md-4"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Duruş Değiştir</button></div>
            <div class="col-md-4"><a class="btn btn-lg btn-secondary" style="height:100px; width:300px; text-align:center" href="@Url.Action("IsDegistir","calisiyor")">İş Değiştir</a></div>
            <div class="col-md-4"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Tanımsız Duruşları Değiştir</button></div>
           
        </div>
        <br />
        <div class="row">
            <div class="col-md-4"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Sonraki İş Seçimi</button></div>
            <div class="col-md-4"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Kalite&Bakım Personeli Çağır</button></div>
            <div class="col-md-4"><a class="btn btn-lg btn-secondary" style="text-align:center; height:100px; width:300px" href="@Url.Action("isBekliyor","isBekliyor")">Geri</a></div>
            @*<div class="col-md-4"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Geri</button></div>*@
        </div>
        <br />
        @*<div class="row">
            <div class="col-md-3"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Hammadde İşlemleri</button></div>
            <div class="col-md-3"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Sonraki İş Seçimi</button></div>
            <div class="col-md-3"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Kalite&Bakım Personeli Çağır</button></div>
            <div class="col-md-3"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Mesajlar[Son 100]</button></div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Ekran Koruyucu</button></div>
            <div class="col-md-3"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Ekran Koruyucuyu Devreye Al</button></div>
            <div class="col-md-3"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">İş Bilgisi Yazdır</button></div>
            <div class="col-md-3"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Son Etiketi Yazdır</button></div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Kalıp Değişimi</button></div>
            <div class="col-md-3"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">I/O Kart Bilgileri</button></div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Onaysız Üretim Fişleri</button></div>
            <div class="col-md-3"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Üst Sisteme Gönderilemeyen Üretim Fişleri</button></div>
            <div class="col-md-3"></div>
            <div class="col-md-3"><a class="btn btn-lg btn-secondary" style="text-align:center; height:100px; width:300px" href="@Url.Action("isBekliyor","isBekliyor")">Geri</a></div>
            <div class="col-md-3"><button class="btn btn-lg btn-secondary" style="height:100px; width:300px">Geri</button></div>
        </div>*@
    </div>



    @*<div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-6">
                        <button class="btn btn-primary btn-lg">İş Bilgileri</button>
                        <button class="btn btn-primary btn-lg" disabled>Duruş Değiştir</button>
                        <button class="btn btn-primary btn-lg">Hammadde İşlemleri</button>
                        <button class="btn btn-primary btn-lg">Ekran Koruyucu</button>
                        <button class="btn btn-primary btn-lg">Kalıp Değişimi</button>
                        <button class="btn btn-primary btn-lg">Onaysız Üretim Fişleri</button>
                    </div>
                    <div class="col-md-6">
                        <button class="btn btn-primary btn-lg">İş Değiştir</button>
                        <button class="btn btn-primary btn-lg">Duruş Değiştir</button>
                        <button class="btn btn-primary btn-lg">Tanımsız Duruşları Değiştir</button>
                        <button class="btn btn-primary btn-lg">Sonraki İş Seçimi</button>
                        <button class="btn btn-primary btn-lg">Ekran Koruyucuyu Devreye Al</button>
                        <button class="btn btn-primary btn-lg">I/O Kart Bilgileri</button>
                        <button class="btn btn-primary btn-lg">Üst Sisteme Gönderilemeyen Üretim Fişleri</button>
                    </div>
                </div>
            </div>

                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-6">
                            <button class="btn btn-primary btn-lg">BAKIM</button>
                            <button class="btn btn-primary btn-lg">KALİTE KONTROL</button>
                            <button class="btn btn-primary btn-lg">Kalite&Bakım Personeli Çağır</button>
                            <button class="btn btn-primary btn-lg">İş Bilgisi Yazdır</button>
                        </div>
                        <div class="col-md-6">
                            <button class="btn btn-primary btn-lg" disabled>Bakım İşemri Kapat</button>
                            <button class="btn btn-primary btn-lg">Enerji Tüketim Bilgisi</button>
                            <button class="btn btn-primary btn-lg">Mesajlar (Son 100)</button>
                            <button class="btn btn-primary btn-lg">BAKIM</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>*@
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

Views/calisiyor/IsDegistir.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>IsDegistir</title>
</head>
<body>
    <header style="text-align:center">İŞ MERKEZİ SEÇ</header>
    <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action">İSTASYON 5|2</a>
        <a href="#" class="list-group-item list-group-item-action">İSTASYON 745|156</a>
        <a href="#" class="list-group-item list-group-item-action">İSTASYON 847|179</a>
        <a href="@Url.Action("IsDegistir2", "calisiyor")" class="list-group-item list-group-item-action">İSTASYON 899|192</a>
        <a href="#" class="list-group-item list-group-item-action">İSTASYON 903|193</a>
        <a href="#" class="list-group-item list-group-item-action">İSTASYON 934|201</a>
        <a href="#" class="list-group-item list-group-item-action">İSTASYON 95|20</a>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

Views/calisiyor/IsDegistir2.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>IsDegistir2</title>
</head>
<body>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>İş emri No</th>
                <th>Baş. Tarihi</th>
                <th>Miktar</th>
                <th>Kapasite</th>
                <th>Üst Sistem No</th>
                <th>İş No</th>
                <th>Operasyon</th>
                <th>Detay</th>
            </tr>
            <tr>
                <td>005881</td>
                <td>4/4/2015</td>
                <td>2588</td>
                <td>1800</td>
                <td>005881</td>
                <td>2296</td>
                <td>ÇEVRE KESME</td>
                <td><a class="btn btn-primary" href='javascript:openwindow();'>Detay</a></td>
            </tr>
            <tr>
                <td>006604</td>
                <td>4/17/2015</td>
                <td>5000</td>
                <td>4800</td>
                <td>006604</td>
                <td>2486</td>
                <td>PROGRASİV</td>
                <td><a class="btn btn-primary" href='javascript:openwindow();'>Detay</a></td>
            </tr>
            <tr>
                <td>006679</td>
                <td>4/18/2015</td>
                <td>2734</td>
                <td>360</td>
                <td>006679</td>
                <td>2513</td>
                <td>FORM VERME</td>
                <td><a class="btn btn-primary" href='javascript:openwindow();'>Detay</a></td>
            </tr>
            <tr>
                <td>007553</td>
                <td>5/9/2015</td>
                <td>6000</td>
                <td>4000</td>
                <td>007553</td>
                <td>2701</td>
                <td>PROGRASİV</td>
                <td><a class="btn btn-primary" href='javascript:openwindow();'>Detay</a></td>
            </tr>
            <tr>
                <td>008096</td>
                <td>5/9/2015</td>
                <td>5000</td>
                <td>4800</td>
                <td>008096</td>
                <td>2761</td>
                <td>PROGRASİV</td>
                <td><a class="btn btn-primary" href='javascript:openwindow();'>Detay</a></td>
            </tr>
            <tr>
                <td>008260</td>
                <td>5/16/2015</td>
                <td>5000</td>
                <td>4800</td>
                <td>008260</td>
                <td>2841</td>
                <td>ÇEVRE KESME</td>
                <td><a class="btn btn-primary" href='javascript:openwindow();'>Detay</a></td>
            </tr>
        </thead>
    </table>

    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <form class="d-flex">
                <input class="form-control me-2" type="search" aria-label="Search">
                <button class="btn btn-success btn-lg" type="submit">Ara</button>
                <button class="btn btn-success btn-lg" type="submit">Listeyi Yenile</button>
                <button class="btn btn-success btn-lg" type="submit">İş Yükle</button>
                <a href='@Url.Action("DigerIslemler", "calisiyor")' class="btn btn-success btn-lg">Geri</a>
            </form>
        </div>
    </nav>

    <script>
    function openwindow()
    {
        var x=window.open('@Url.Action("IsDetayi2","calisiyor")',target = '_blank', width = '400px', height = '400px');
    }
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

Views/isBekliyor/isbekliyor.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>isbekliyor</title>
</head>
<body>
    <div class="row">
        <div class="col-md-6" style="background-color:darkred">
            <p style="color:white"><strong>İSTASYON 899</strong></p>
        </div>

        <div class="col-md-6" style="background-color:dimgray"><p style="color:white"><strong>İŞ BEKLİYOR</strong></p></div>
    </div>

    <div class="container-fluid" style="background-color:darkslategrey; height:100px">
        <div class="row">
            <div class="col-md-6">
                <label style="color:white">İŞ NO | PLAN. İŞ MİKTARI</label><br />
                <label style="color:white">KALAN MİKTAR [ADET]</label>
            </div>
            <div class="col-md-6">
                <label style="color:white"><strong>ADET</strong></label><br />
            </div>
        </div>
    </div>

    <div class="container-fluid" style="background-color:darkred; height:80px">
        <div class="row">
            <div class="col-md-6">
                <label style="color:white">STOK</label><br />
                <label style="color:white">STOK ADI 2</label>
            </div>
            <div class="col-md-6">
                <label style="color:white">İŞ EMRİ NO</label><br />
                <label style="color:white">İŞE BAŞLAMA</label><br />
                <label style="color:white">GEÇEN SÜRE</label>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <th scope="row">PERSONEL</th>
                            <td> </td>
                        </tr>
                        <tr>
                            <th scope="row">OPERASYON</th>
                            <td> </td>
                        </tr>
                        <tr>
                            <th scope="row">ANLIK DURUŞ SÜRESİ</th>
                            <td>43 sn</td>
                        </tr>
                        <tr>
                            <th scope="row">VARDİYA ÜRETİMİ</th>
                            <td>485</td>
                        </tr>
                        <tr>
                            <th scope="row">VARDİYA DURUŞ SÜRESİ</th>
                            <td>8 sa 49 dk</td>
                        </tr>
                        <tr>
                            <th scope="row">RANDIMAN (Son 8 saat)</th>
                            <td>%2</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="col-md-6">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <th scope="row">HATA</th>
                            <td>0</td>
                        </tr>
                        <tr>
                            <th scope="row">TAKİP NO</th>
                            <td> </td>
                        </tr>
                        <tr>
                            <th scope="row">EKİPMAN</th>
                            <td>43 sn</td>
                        </tr>
                        <tr>
                            <th scope="row">ANLIK/V. ORT. HIZ</th>
                            <td>4000/0</td>
                        </tr>
                        <tr>
                            <th scope="row">ÇEVRİM G/P</th>
                            <td>.9/0</td>
                        </tr>
                        <tr>
                            <th scope="row">PLAN. KAPASİTE</th>
                            <td>1440 Ad/Sa</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="text-center">
        <a class="btn btn-lg btn-success" style="text-align:center" href="@Url.Action("isYukle","isBekliyor")">İş Yükle</a>
        <button type="button" class="btn btn-success btn-lg">Duruş Tanımla</button>
        <button type="button" class="btn btn-success btn-lg">Personel İşlemleri</button>
        <button type="button" class="btn btn-success btn-lg" disabled>Hata Girişi</button>
        <button type="button" class="btn btn-success btn-lg">Vardiya Bilgileri</button>
        <button type="button" class="btn btn-success btn-lg">İş Parametreleri</button>
        <a class="btn btn-lg btn-success" style="text-align:center" href="@Url.Action("DigerIslemler","calisiyor")">Diğer İşlemler</a>
   
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>

</html>